[project]
name = "mcp_demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mcp>=1.9.2",
]

[tool.uv.workspace]
members = [
    "mcp_demo",
    "mcp_project",
]
